/* LALBuildInfo.c: generated by Makefile */
const char *const lalConfigureArgs = "'--disable-option-checking' '--prefix=/home/daniel/.virtualenvs/lal-minke' '--enable-silent-rules' '--enable-swig-python' 'LIBS=-L//home/daniel/.virtualenvs/lal-minke/lib/' 'LDFLAGS=-L//home/daniel/.virtualenvs/lal-minke/lib/' 'CFLAGS=-L/home/daniel/.virtualenvs/lal-minke/include' 'LIBFRAME_LIBS=-L//home/daniel/.virtualenvs/lal-minke/lib/' '--cache-file=/dev/null' '--srcdir=.'";
const char *const lalConfigureDate = "2017-05-11T08:11:29-0500";
const char *const lalBuildDate = "2017-05-11T08:13:21-0500";
