/* LALBuildInfoHeader.h: generated by Makefile */
#define LAL_CONFIGURE_ARGS "'--disable-option-checking' '--prefix=/home/daniel/.virtualenvs/IGRlaptop21/minke' '--enable-silent-rules' '--enable-swig-python' 'LIBS=-L//home/daniel/.virtualenvs/IGRlaptop21/minke/lib/' 'LDFLAGS=-L//home/daniel/.virtualenvs/IGRlaptop21/minke/lib/' 'CFLAGS=-L/home/daniel/.virtualenvs/IGRlaptop21/minke/include' 'LIBFRAME_LIBS=-L//home/daniel/.virtualenvs/IGRlaptop21/minke/lib/' '--cache-file=/dev/null' '--srcdir=.'"
#define LAL_CONFIGURE_DATE "2017-06-19T16:01:34-0400"
#define LAL_BUILD_DATE "2017-06-19T16:02:46-0400"
